using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace StockNote.Models
{
    /// <summary>
    /// StockNote based class to inherit from all StockNote objects
    /// </summary>
    public class BasedModel
    {
        /// <summary>
        /// StockNote ID which will be generated by SQL server
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid ID { get; set; }
        /// <summary>
        /// For soft delete. Tefault is True. 
        /// If record is deleted, this field will be updated as False.
        /// </summary>
        [Required]
        [Column("IsActive", TypeName = "bit")]
        [DefaultValue(true)]
        public bool IsActive { get; set; } = true;
        /// <summary>
        /// Created user, get from current login account
        /// </summary>
        [Column("CreatedBy", TypeName = "nvarchar(50)")]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Created time, get from current date/time
        /// </summary>
        //[Column("CreatedOn", TypeName = "datetime")]
        //public DateTime? CreatedOn { get; set; } // Change as Shadow Property at OnModelCreating
        /// <summary>
        /// Modified user, get from current login account
        /// </summary>
        [Column("ModifiedBy", TypeName = "nvarchar(50)")]
        public string ModifiedBy { get; set; }
        /// <summary>
        /// Modified time, get from current date/time
        /// </summary>
        //[Column("ModifiedOn", TypeName = "datetime")]
        //public DateTime? ModifiedOn { get; set; } // Change as Shadow Property at OnModelCreating
        //[Column("RowVersion", TypeName = "timestamp")]
        //[Timestamp]
        //public byte[] RowVersion { get; set; } // Change as Shadow Property at OnModelCreating

    }
}